name: pokeapp
description: Projeto Lista de Pokémons.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "assets/pokemon_icon.png" 
  android: true
  ios: true

flutter_native_splash: 

  android: true
  ios: true
  web: true 

  color: "#D9E7E2"
  image: "assets/splash_squirtle.png"

  android_gravity: center
  ios_content_mode: center
  web_image_mode: center


flutter:
  uses-material-design: true
  assets:
  - assets/